/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.8
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * APIError.h
 *
 * RFC 7807 compliant problem details object representing an API error.
 */

#ifndef XYO_MODEL_APIError_H_
#define XYO_MODEL_APIError_H_

#include <boost/optional.hpp>

#include "XYOSDK/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace xyo_model {



/// <summary>
/// RFC 7807 compliant problem details object representing an API error.
/// </summary>
class  APIError
    : public ModelBase
{
public:
    APIError();
    virtual ~APIError();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// APIError members


    /// <summary>
    /// A URI reference identifying the problem type.
    /// </summary>
    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(const utility::string_t& value);

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    utility::string_t getTitle() const;
    bool titleIsSet() const;
    void unsetTitle();
    void setTitle(const utility::string_t& value);

    /// <summary>
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    /// </summary>
    int32_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(int32_t value);

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    utility::string_t getDetail() const;
    bool detailIsSet() const;
    void unsetDetail();
    void setDetail(const utility::string_t& value);

    /// <summary>
    /// A URI reference identifying the specific occurrence of the problem.
    /// </summary>
    utility::string_t getInstance() const;
    bool instanceIsSet() const;
    void unsetInstance();
    void setInstance(const utility::string_t& value);


protected:
    utility::string_t m_Type;
    bool m_TypeIsSet;

    utility::string_t m_Title;
    bool m_TitleIsSet;

    int32_t m_Status;
    bool m_StatusIsSet;

    utility::string_t m_Detail;
    bool m_DetailIsSet;

    utility::string_t m_Instance;
    bool m_InstanceIsSet;

};


}

#endif /* XYO_MODEL_APIError_H_ */
