/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EnrichmentResponse.h
 *
 * 
 */

#ifndef XYO_MODEL_EnrichmentResponse_H_
#define XYO_MODEL_EnrichmentResponse_H_

#include <boost/optional.hpp>

#include "XYOSDK/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace xyo_model {



class  EnrichmentResponse
    : public ModelBase
{
public:
    EnrichmentResponse();
    virtual ~EnrichmentResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// EnrichmentResponse members


    /// <summary>
    /// Merchant is the name of the merchant.
    /// </summary>
    utility::string_t getMerchant() const;
    bool merchantIsSet() const;
    void unsetMerchant();
    void setMerchant(const utility::string_t& value);

    /// <summary>
    /// Description is a brief description of the merchant.
    /// </summary>
    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();
    void setDescription(const utility::string_t& value);

    /// <summary>
    /// Categories lists categories fitting the description of the merchant.
    /// </summary>
    std::vector<utility::string_t> getCategories() const;
    bool categoriesIsSet() const;
    void unsetCategories();
    void setCategories(const std::vector<utility::string_t>& value);

    /// <summary>
    /// Logo is a base64-encoded PNG or JPEG representing the merchant logo.
    /// </summary>
    utility::string_t getLogo() const;
    bool logoIsSet() const;
    void unsetLogo();
    void setLogo(const utility::string_t& value);

    /// <summary>
    /// Location describes the country and city. May be empty if the API returns null.
    /// </summary>
    utility::string_t getLocation() const;
    bool locationIsSet() const;
    void unsetLocation();
    void setLocation(const utility::string_t& value);

    /// <summary>
    /// Address describes the exact address of purchase. May be empty if the API returns null.
    /// </summary>
    utility::string_t getAddress() const;
    bool addressIsSet() const;
    void unsetAddress();
    void setAddress(const utility::string_t& value);


protected:
    utility::string_t m_Merchant;
    bool m_MerchantIsSet;

    utility::string_t m_Description;
    bool m_DescriptionIsSet;

    std::vector<utility::string_t> m_Categories;
    bool m_CategoriesIsSet;

    utility::string_t m_Logo;
    bool m_LogoIsSet;

    utility::string_t m_Location;
    bool m_LocationIsSet;

    utility::string_t m_Address;
    bool m_AddressIsSet;

};


}

#endif /* XYO_MODEL_EnrichmentResponse_H_ */
