/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.9
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EnrichTransactionCollectionResponse.h
 *
 * 
 */

#ifndef XYO_MODEL_EnrichTransactionCollectionResponse_H_
#define XYO_MODEL_EnrichTransactionCollectionResponse_H_

#include <boost/optional.hpp>

#include "XYOSDK/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace xyo_model {



class  EnrichTransactionCollectionResponse
    : public ModelBase
{
public:
    EnrichTransactionCollectionResponse();
    virtual ~EnrichTransactionCollectionResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// EnrichTransactionCollectionResponse members


    /// <summary>
    /// ID is the work ID for the enrichment request.
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(const utility::string_t& value);

    /// <summary>
    /// Link is the URL to the downloadable tar.gz results archive.
    /// </summary>
    utility::string_t getLink() const;
    bool linkIsSet() const;
    void unsetLink();
    void setLink(const utility::string_t& value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;

    utility::string_t m_Link;
    bool m_LinkIsSet;

};


}

#endif /* XYO_MODEL_EnrichTransactionCollectionResponse_H_ */
