/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.8
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EnrichmentCollectionStatusResponse.h
 *
 * 
 */

#ifndef XYO_MODEL_EnrichmentCollectionStatusResponse_H_
#define XYO_MODEL_EnrichmentCollectionStatusResponse_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "XYOSDK/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace xyo_model {



class  EnrichmentCollectionStatusResponse
    : public ModelBase
{
public:
    EnrichmentCollectionStatusResponse();
    virtual ~EnrichmentCollectionStatusResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// EnrichmentCollectionStatusResponse members

    enum class StatusEnum
    {
        READY,
        FAILED,
        PENDING,
    };
    /// <summary>
    /// Status represents the processing state of a bulk enrichment job.
    /// </summary>

    StatusEnum toStatusEnum(const utility::string_t& value) const;
    const utility::string_t fromStatusEnum(const StatusEnum value) const;


    /// <summary>
    /// Status represents the processing state of a bulk enrichment job.
    /// </summary>
    StatusEnum getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const StatusEnum value);


protected:
    StatusEnum m_Status;
    bool m_StatusIsSet;

};


}

#endif /* XYO_MODEL_EnrichmentCollectionStatusResponse_H_ */
