/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EnrichTransactions_request_inner.h
 *
 * 
 */

#ifndef XYO_MODEL_EnrichTransactions_request_inner_H_
#define XYO_MODEL_EnrichTransactions_request_inner_H_

#include <boost/optional.hpp>

#include "XYOSDK/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace xyo_model {



class  EnrichTransactions_request_inner
    : public ModelBase
{
public:
    EnrichTransactions_request_inner();
    virtual ~EnrichTransactions_request_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// EnrichTransactions_request_inner members


    /// <summary>
    /// Content is the payment description, maximum 128 characters.
    /// </summary>
    utility::string_t getContent() const;
    bool contentIsSet() const;
    void unsetContent();
    void setContent(const utility::string_t& value);

    /// <summary>
    /// CountryCode is the ISO 3166-1 alpha-2 two-character country code.
    /// </summary>
    utility::string_t getCountryCode() const;
    bool countryCodeIsSet() const;
    void unsetCountryCode();
    void setCountryCode(const utility::string_t& value);


protected:
    utility::string_t m_Content;
    bool m_ContentIsSet;

    utility::string_t m_CountryCode;
    bool m_CountryCodeIsSet;

};


}

#endif /* XYO_MODEL_EnrichTransactions_request_inner_H_ */
