/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.8
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ErrorResponse.h
 *
 * Standard error response envelope containing a list of RFC 7807 problem details errors.
 */

#ifndef XYO_MODEL_ErrorResponse_H_
#define XYO_MODEL_ErrorResponse_H_

#include <boost/optional.hpp>

#include "XYOSDK/ModelBase.h"

#include "XYOSDK/model/APIError.h"
#include <vector>

namespace xyo_model {

class APIError;


/// <summary>
/// Standard error response envelope containing a list of RFC 7807 problem details errors.
/// </summary>
class  ErrorResponse
    : public ModelBase
{
public:
    ErrorResponse();
    virtual ~ErrorResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ErrorResponse members


    /// <summary>
    /// List of problem details errors returned by the API.
    /// </summary>
    std::vector<std::shared_ptr<APIError>> getErrors() const;
    bool errorsIsSet() const;
    void unsetErrors();
    void setErrors(const std::vector<std::shared_ptr<APIError>>& value);


protected:
    std::vector<std::shared_ptr<APIError>> m_Errors;
    bool m_ErrorsIsSet;

};


}

#endif /* XYO_MODEL_ErrorResponse_H_ */
