/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "XYOSDK/model/EnrichTransactionCollectionResponse.h"

namespace xyo_model {

EnrichTransactionCollectionResponse::EnrichTransactionCollectionResponse()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Link = utility::conversions::to_string_t("");
    m_LinkIsSet = false;
}

EnrichTransactionCollectionResponse::~EnrichTransactionCollectionResponse()
{
}

void EnrichTransactionCollectionResponse::validate()
{
    // TODO: implement validation
}

web::json::value EnrichTransactionCollectionResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_LinkIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("link"))] = ModelBase::toJson(m_Link);
    }

    return val;
}

bool EnrichTransactionCollectionResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("link"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("link")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLink;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLink);
            setLink(refVal_setLink);
            
        }
    }
    return ok;
}

void EnrichTransactionCollectionResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_LinkIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("link")), m_Link));
    }
}

bool EnrichTransactionCollectionResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("link"))))
    {
        utility::string_t refVal_setLink;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("link"))), refVal_setLink );
        setLink(refVal_setLink);
    }
    return ok;
}


utility::string_t EnrichTransactionCollectionResponse::getId() const
{
    return m_Id;
}


void EnrichTransactionCollectionResponse::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool EnrichTransactionCollectionResponse::idIsSet() const
{
    return m_IdIsSet;
}

void EnrichTransactionCollectionResponse::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t EnrichTransactionCollectionResponse::getLink() const
{
    return m_Link;
}


void EnrichTransactionCollectionResponse::setLink(const utility::string_t& value)
{
    m_Link = value;
    m_LinkIsSet = true;
}

bool EnrichTransactionCollectionResponse::linkIsSet() const
{
    return m_LinkIsSet;
}

void EnrichTransactionCollectionResponse::unsetLink()
{
    m_LinkIsSet = false;
}

}


