/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "XYOSDK/model/EnrichmentCollectionStatusResponse.h"

namespace xyo_model {

EnrichmentCollectionStatusResponse::EnrichmentCollectionStatusResponse()
{
    m_StatusIsSet = false;
}

EnrichmentCollectionStatusResponse::~EnrichmentCollectionStatusResponse()
{
}

void EnrichmentCollectionStatusResponse::validate()
{
    // TODO: implement validation
}

web::json::value EnrichmentCollectionStatusResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_StatusIsSet)
    {
        
        utility::string_t refVal = fromStatusEnum(m_Status);
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(refVal);
        
    }

    return val;
}

bool EnrichmentCollectionStatusResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            
            setStatus(toStatusEnum(refVal_setStatus));
            
        }
    }
    return ok;
}

void EnrichmentCollectionStatusResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), fromStatusEnum(m_Status)));
    }
}

bool EnrichmentCollectionStatusResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        utility::string_t refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(toStatusEnum(refVal_setStatus));
    }
    return ok;
}

EnrichmentCollectionStatusResponse::StatusEnum EnrichmentCollectionStatusResponse::toStatusEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("READY")) {
        return StatusEnum::READY;
    }
    
    if (value == utility::conversions::to_string_t("FAILED")) {
        return StatusEnum::FAILED;
    }
    
    if (value == utility::conversions::to_string_t("PENDING")) {
        return StatusEnum::PENDING;
    }
    
    throw std::invalid_argument("Invalid value for conversion to StatusEnum");
}


const utility::string_t EnrichmentCollectionStatusResponse::fromStatusEnum(const StatusEnum value) const
{
    switch(value)
    {
        
        case StatusEnum::READY: return utility::conversions::to_string_t("READY");
        
        case StatusEnum::FAILED: return utility::conversions::to_string_t("FAILED");
        
        case StatusEnum::PENDING: return utility::conversions::to_string_t("PENDING");
        
    }
}


EnrichmentCollectionStatusResponse::StatusEnum EnrichmentCollectionStatusResponse::getStatus() const
{
    return m_Status;
}


void EnrichmentCollectionStatusResponse::setStatus(const StatusEnum value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool EnrichmentCollectionStatusResponse::statusIsSet() const
{
    return m_StatusIsSet;
}

void EnrichmentCollectionStatusResponse::unsetStatus()
{
    m_StatusIsSet = false;
}

}


