/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.8
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "XYOSDK/model/EnrichTransactions_request_inner.h"

namespace xyo_model {

EnrichTransactions_request_inner::EnrichTransactions_request_inner()
{
    m_Content = utility::conversions::to_string_t("");
    m_ContentIsSet = false;
    m_CountryCode = utility::conversions::to_string_t("");
    m_CountryCodeIsSet = false;
}

EnrichTransactions_request_inner::~EnrichTransactions_request_inner()
{
}

void EnrichTransactions_request_inner::validate()
{
    // TODO: implement validation
}

web::json::value EnrichTransactions_request_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ContentIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("content"))] = ModelBase::toJson(m_Content);
    }
    if(m_CountryCodeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("countryCode"))] = ModelBase::toJson(m_CountryCode);
    }

    return val;
}

bool EnrichTransactions_request_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("content"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("content")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setContent;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContent);
            setContent(refVal_setContent);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("countryCode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("countryCode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCountryCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCountryCode);
            setCountryCode(refVal_setCountryCode);
            
        }
    }
    return ok;
}

void EnrichTransactions_request_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ContentIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("content")), m_Content));
    }
    if(m_CountryCodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("countryCode")), m_CountryCode));
    }
}

bool EnrichTransactions_request_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("content"))))
    {
        utility::string_t refVal_setContent;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("content"))), refVal_setContent );
        setContent(refVal_setContent);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("countryCode"))))
    {
        utility::string_t refVal_setCountryCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("countryCode"))), refVal_setCountryCode );
        setCountryCode(refVal_setCountryCode);
    }
    return ok;
}


utility::string_t EnrichTransactions_request_inner::getContent() const
{
    return m_Content;
}


void EnrichTransactions_request_inner::setContent(const utility::string_t& value)
{
    m_Content = value;
    m_ContentIsSet = true;
}

bool EnrichTransactions_request_inner::contentIsSet() const
{
    return m_ContentIsSet;
}

void EnrichTransactions_request_inner::unsetContent()
{
    m_ContentIsSet = false;
}
utility::string_t EnrichTransactions_request_inner::getCountryCode() const
{
    return m_CountryCode;
}


void EnrichTransactions_request_inner::setCountryCode(const utility::string_t& value)
{
    m_CountryCode = value;
    m_CountryCodeIsSet = true;
}

bool EnrichTransactions_request_inner::countryCodeIsSet() const
{
    return m_CountryCodeIsSet;
}

void EnrichTransactions_request_inner::unsetCountryCode()
{
    m_CountryCodeIsSet = false;
}

}


