/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.8
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "XYOSDK/model/EnrichmentResponse.h"

namespace xyo_model {

EnrichmentResponse::EnrichmentResponse()
{
    m_Merchant = utility::conversions::to_string_t("");
    m_MerchantIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_CategoriesIsSet = false;
    m_Logo = utility::conversions::to_string_t("");
    m_LogoIsSet = false;
    m_Location = utility::conversions::to_string_t("");
    m_LocationIsSet = false;
    m_Address = utility::conversions::to_string_t("");
    m_AddressIsSet = false;
}

EnrichmentResponse::~EnrichmentResponse()
{
}

void EnrichmentResponse::validate()
{
    // TODO: implement validation
}

web::json::value EnrichmentResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_MerchantIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("merchant"))] = ModelBase::toJson(m_Merchant);
    }
    if(m_DescriptionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_CategoriesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("categories"))] = ModelBase::toJson(m_Categories);
    }
    if(m_LogoIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("logo"))] = ModelBase::toJson(m_Logo);
    }
    if(m_LocationIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("location"))] = ModelBase::toJson(m_Location);
    }
    if(m_AddressIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("address"))] = ModelBase::toJson(m_Address);
    }

    return val;
}

bool EnrichmentResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("merchant"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("merchant")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMerchant;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMerchant);
            setMerchant(refVal_setMerchant);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("categories"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("categories")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setCategories;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCategories);
            setCategories(refVal_setCategories);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("logo"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("logo")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLogo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLogo);
            setLogo(refVal_setLogo);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("location"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("location")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLocation;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLocation);
            setLocation(refVal_setLocation);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("address"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("address")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAddress;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAddress);
            setAddress(refVal_setAddress);
            
        }
    }
    return ok;
}

void EnrichmentResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_MerchantIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("merchant")), m_Merchant));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_CategoriesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("categories")), m_Categories));
    }
    if(m_LogoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("logo")), m_Logo));
    }
    if(m_LocationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("location")), m_Location));
    }
    if(m_AddressIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("address")), m_Address));
    }
}

bool EnrichmentResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("merchant"))))
    {
        utility::string_t refVal_setMerchant;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("merchant"))), refVal_setMerchant );
        setMerchant(refVal_setMerchant);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("categories"))))
    {
        std::vector<utility::string_t> refVal_setCategories;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("categories"))), refVal_setCategories );
        setCategories(refVal_setCategories);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("logo"))))
    {
        utility::string_t refVal_setLogo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("logo"))), refVal_setLogo );
        setLogo(refVal_setLogo);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("location"))))
    {
        utility::string_t refVal_setLocation;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("location"))), refVal_setLocation );
        setLocation(refVal_setLocation);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("address"))))
    {
        utility::string_t refVal_setAddress;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("address"))), refVal_setAddress );
        setAddress(refVal_setAddress);
    }
    return ok;
}


utility::string_t EnrichmentResponse::getMerchant() const
{
    return m_Merchant;
}


void EnrichmentResponse::setMerchant(const utility::string_t& value)
{
    m_Merchant = value;
    m_MerchantIsSet = true;
}

bool EnrichmentResponse::merchantIsSet() const
{
    return m_MerchantIsSet;
}

void EnrichmentResponse::unsetMerchant()
{
    m_MerchantIsSet = false;
}
utility::string_t EnrichmentResponse::getDescription() const
{
    return m_Description;
}


void EnrichmentResponse::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool EnrichmentResponse::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void EnrichmentResponse::unsetDescription()
{
    m_DescriptionIsSet = false;
}
std::vector<utility::string_t> EnrichmentResponse::getCategories() const
{
    return m_Categories;
}


void EnrichmentResponse::setCategories(const std::vector<utility::string_t>& value)
{
    m_Categories = value;
    m_CategoriesIsSet = true;
}

bool EnrichmentResponse::categoriesIsSet() const
{
    return m_CategoriesIsSet;
}

void EnrichmentResponse::unsetCategories()
{
    m_CategoriesIsSet = false;
}
utility::string_t EnrichmentResponse::getLogo() const
{
    return m_Logo;
}


void EnrichmentResponse::setLogo(const utility::string_t& value)
{
    m_Logo = value;
    m_LogoIsSet = true;
}

bool EnrichmentResponse::logoIsSet() const
{
    return m_LogoIsSet;
}

void EnrichmentResponse::unsetLogo()
{
    m_LogoIsSet = false;
}
utility::string_t EnrichmentResponse::getLocation() const
{
    return m_Location;
}


void EnrichmentResponse::setLocation(const utility::string_t& value)
{
    m_Location = value;
    m_LocationIsSet = true;
}

bool EnrichmentResponse::locationIsSet() const
{
    return m_LocationIsSet;
}

void EnrichmentResponse::unsetLocation()
{
    m_LocationIsSet = false;
}
utility::string_t EnrichmentResponse::getAddress() const
{
    return m_Address;
}


void EnrichmentResponse::setAddress(const utility::string_t& value)
{
    m_Address = value;
    m_AddressIsSet = true;
}

bool EnrichmentResponse::addressIsSet() const
{
    return m_AddressIsSet;
}

void EnrichmentResponse::unsetAddress()
{
    m_AddressIsSet = false;
}

}


