/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.8
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "XYOSDK/model/ErrorResponse.h"

namespace xyo_model {

ErrorResponse::ErrorResponse()
{
    m_ErrorsIsSet = false;
}

ErrorResponse::~ErrorResponse()
{
}

void ErrorResponse::validate()
{
    // TODO: implement validation
}

web::json::value ErrorResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ErrorsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("errors"))] = ModelBase::toJson(m_Errors);
    }

    return val;
}

bool ErrorResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("errors"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("errors")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<APIError>> refVal_setErrors;
            ok &= ModelBase::fromJson(fieldValue, refVal_setErrors);
            setErrors(refVal_setErrors);
            
        }
    }
    return ok;
}

void ErrorResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ErrorsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("errors")), m_Errors));
    }
}

bool ErrorResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("errors"))))
    {
        std::vector<std::shared_ptr<APIError>> refVal_setErrors;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("errors"))), refVal_setErrors );
        setErrors(refVal_setErrors);
    }
    return ok;
}


std::vector<std::shared_ptr<APIError>> ErrorResponse::getErrors() const
{
    return m_Errors;
}


void ErrorResponse::setErrors(const std::vector<std::shared_ptr<APIError>>& value)
{
    m_Errors = value;
    m_ErrorsIsSet = true;
}

bool ErrorResponse::errorsIsSet() const
{
    return m_ErrorsIsSet;
}

void ErrorResponse::unsetErrors()
{
    m_ErrorsIsSet = false;
}

}


