/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.9
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "XYOSDK/JsonBody.h"

namespace xyo_model {

JsonBody::JsonBody( const web::json::value& json)
    : m_Json(json)
{
}

JsonBody::~JsonBody()
{
}

void JsonBody::writeTo( std::ostream& target )
{
    m_Json.serialize(target);
}

}
