/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AnyType.h
 *
 * This is the implementation of an any JSON type.
 */

#ifndef XYO_MODEL_AnyType_H_
#define XYO_MODEL_AnyType_H_


#include "XYOSDK/Object.h"

#include <cpprest/details/basic_types.h>
#include <cpprest/json.h>

namespace xyo_model {

class  AnyType : public Object {
public:
  AnyType();
  virtual ~AnyType();

  /////////////////////////////////////////////
  /// ModelBase overrides
  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

private:
  web::json::value m_value;
};

}

#endif /* XYO_MODEL_AnyType_H_ */
