/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 2.0.9
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EnrichmentApi.h
 *
 * 
 */

#ifndef XYO_API_EnrichmentApi_H_
#define XYO_API_EnrichmentApi_H_



#include "XYOSDK/ApiClient.h"

#include "XYOSDK/model/EnrichTransactionCollectionResponse.h"
#include "XYOSDK/model/EnrichTransactions_request_inner.h"
#include "XYOSDK/model/EnrichmentCollectionStatusResponse.h"
#include "XYOSDK/model/EnrichmentRequest.h"
#include "XYOSDK/model/EnrichmentResponse.h"
#include "XYOSDK/model/ErrorResponse.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace xyo_api {

using namespace xyo_model;



class  EnrichmentApi 
{
public:

    explicit EnrichmentApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~EnrichmentApi();

    /// <summary>
    /// Transaction Enrichment
    /// </summary>
    /// <remarks>
    /// Enrich a single financial transaction synchronously.
    /// </remarks>
    /// <param name="enrichmentRequest">Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code.</param>
    /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<EnrichmentResponse>> enrichTransaction(
        std::shared_ptr<EnrichmentRequest> enrichmentRequest,
        boost::optional<utility::string_t> xCorrelationID,
        boost::optional<utility::string_t> traceparent
    ) const;
    /// <summary>
    /// Transaction Enrichments
    /// </summary>
    /// <remarks>
    /// Enrich a collection of financial transactions asynchronously.
    /// </remarks>
    /// <param name="enrichTransactionsRequestInner">Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing.</param>
    /// <param name="xApiUser">Optional identifier for the API user or tenant. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<EnrichTransactionCollectionResponse>> enrichTransactions(
        std::vector<std::shared_ptr<EnrichTransactions_request_inner>> enrichTransactionsRequestInner,
        boost::optional<utility::string_t> xApiUser,
        boost::optional<utility::string_t> xCorrelationID,
        boost::optional<utility::string_t> traceparent
    ) const;
    /// <summary>
    /// Transaction Enrichments Status
    /// </summary>
    /// <remarks>
    /// Get the status of an asynchronous bulk enrichment job.
    /// </remarks>
    /// <param name="id">The unique identifier of the asynchronous bulk enrichment job.</param>
    /// <param name="xApiUser">Optional identifier for the API user or tenant. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="xCorrelationID">Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="traceparent">Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<EnrichmentCollectionStatusResponse>> getEnrichmentStatus(
        utility::string_t id,
        boost::optional<utility::string_t> xApiUser,
        boost::optional<utility::string_t> xCorrelationID,
        boost::optional<utility::string_t> traceparent
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}

#endif /* XYO_API_EnrichmentApi_H_ */

