/**
 * XYO RESTful Transaction Enrichment API
 * RESTful API for enriching financial transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.24.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EnrichmentApi.h
 *
 * 
 */

#ifndef XYO_API_EnrichmentApi_H_
#define XYO_API_EnrichmentApi_H_



#include "XYOSDK/ApiClient.h"
#include "XYOSDK/AnyType.h"

#include "XYOSDK/model/EnrichTransactionCollectionResponse.h"
#include "XYOSDK/model/EnrichTransactions_request_inner.h"
#include "XYOSDK/model/EnrichmentCollectionStatusResponse.h"
#include "XYOSDK/model/EnrichmentRequest.h"
#include "XYOSDK/model/EnrichmentResponse.h"
#include "XYOSDK/model/ErrorResponse.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace xyo_api {

using namespace xyo_model;



class  EnrichmentApi 
{
public:

    explicit EnrichmentApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~EnrichmentApi();

    /// <summary>
    /// Transaction Enrichment
    /// </summary>
    /// <remarks>
    /// Enrich a single financial transaction synchronously.
    /// </remarks>
    /// <param name="enrichmentRequest"> (optional)</param>
    pplx::task<std::shared_ptr<EnrichmentResponse>> enrichTransaction(
        boost::optional<std::shared_ptr<EnrichmentRequest>> enrichmentRequest
    ) const;
    /// <summary>
    /// Transaction Enrichments
    /// </summary>
    /// <remarks>
    /// Enrich a collection of financial transactions asynchronously.
    /// </remarks>
    /// <param name="xApiUser"> (optional, default to nullptr)</param>
    /// <param name="enrichTransactionsRequestInner"> (optional)</param>
    pplx::task<std::shared_ptr<EnrichTransactionCollectionResponse>> enrichTransactions(
        boost::optional<std::shared_ptr<AnyType>> xApiUser,
        boost::optional<std::vector<std::shared_ptr<EnrichTransactions_request_inner>>> enrichTransactionsRequestInner
    ) const;
    /// <summary>
    /// Transaction Enrichments Status
    /// </summary>
    /// <remarks>
    /// Get the status of an asynchronous bulk enrichment job.
    /// </remarks>
    /// <param name="id"></param>
    /// <param name="xApiUser"> (optional, default to nullptr)</param>
    pplx::task<std::shared_ptr<EnrichmentCollectionStatusResponse>> getEnrichmentStatus(
        utility::string_t id,
        boost::optional<std::shared_ptr<AnyType>> xApiUser
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}

#endif /* XYO_API_EnrichmentApi_H_ */

